### ISSUE TITLE
[START HERE!] Outreachy #1: Set up a development environment with the UNICEF Inventory example site

### ISSUE THREAD

**Issue by jwflory** [unicef/inventory-hugo-theme#59]
_Welcome to Outreachy 2022 with @unicef! This is an issue meant for newcomers working on the UNICEF Inventory project. Before working on this project, you should read the [full project profile](https://www.outreachy.org/outreachy-may-2022-internship-round/communities/unicef/#improve-uiux-of-unicef-inventory-and-redesign-site) from the Outreachy website for more background. It will make your first contribution and efforts here easier!_

# Summary

Set up your development environment with Hugo and the UNICEF Inventory theme's example site.

# Background

When you are working on the UNICEF Inventory theme, you will need to test and verify your changes as you work on the theme. The easiest way to do that is to run Hugo on the example site included in this repository. You will be able to test your changes out and see them in real-time before submitting a Pull Request for review.

The purpose of this issue is a milestone in your Outreachy application to @unicef. To complete this issue, your mission is to set up your development environment and share proof of that by uploading a screenshot to this GitHub Issue. Once you have done so, you will be "assigned" to this GitHub Issue as verification you have completed the requirement. You can also provide help and guidance to others who ask for help in this issue if you wish.

This issue will remain open for the full contribution period of this Outreachy round and will close on 22 April (end of contribution period).

# Details

To complete this issue, do the following:

1. Install Hugo ([_see docs_](https://gohugo.io/getting-started/installing/)). _Hint_: The best way to go is to use a precompiled binary with a more recent version of Hugo.
1. Clone this git repository to your machine.
1. Edit the example site `config.yml` to change the site `title` to your GitHub username and change the `params.primary_color` to your favorite color.
1. Run `hugo serve` in the terminal and open the example site to see your changes.
1. Take a screenshot of the local site preview from your browser.
1. Upload the screenshot to this GitHub Issue.

_Hint_: The contributing guidelines have extra help if you get stuck. `#TODO` Write contributing guidelines for the Inventory theme.

# Outcome

- You successfully installed Hugo, made changes to the example site, and saw them live from a local preview on your machine.
- You are now ready to move on to the next Outreachy applicant issue, #60.

**Comment by Yavnikaa** [comment]
![Screenshot (207)](https://user-images.githubusercontent.com/56485761/158051338-eb27e51c-fb88-4485-95d3-597ae695bc99.png)

I have done as directed on my local machine. Hope this is correct! :))

**Comment by steph237** [comment]
I cloned the repo and followed the instructions. I hope I did it right
![un inventory](https://user-images.githubusercontent.com/43364084/158140056-cd9dd566-4e22-4238-8f6e-f26c948b7561.png)
.

**Comment by jwflory** [comment]
Thanks @Yavnikaa, @steph237, & @BeeBombshell, looking good! 👍🏻

**Comment by janvi01** [comment]
Hello, @jwflory I have set up as mentioned, please have a look. Thanks!

<img width="1440" alt="Screenshot 2022-03-15 at 11 04 29 AM" src="https://user-images.githubusercontent.com/34344234/158313652-928e6639-f676-4ff3-b777-e6092aa511b9.png">

**Comment by mmldco** [comment]
My submission
![Screenshot 2022-03-11 at 2 31 21 AM](https://user-images.githubusercontent.com/69677286/158701030-0a85c2e2-4ca5-492b-bb33-c5248205c364.png)

**Comment by Neha9849** [comment]
Here is mine
![image](https://user-images.githubusercontent.com/85057583/158769252-5cd0eb17-535e-4a95-be59-766e539a2ead.png)

**Comment by roli25** [comment]
Hello @jwflory 
I have followed the instructions. 
Kindly have a look.
![Screenshot (456)](https://user-images.githubusercontent.com/59510531/158792323-fc951f24-61af-4141-bd44-cef12f56e11d.png)

**Comment by jwflory** [comment]
@mmldco @Neha9849 @roli25 All looks right, thanks for following up here!

**Comment by gnikita432** [comment]
Hii @jwflory  I have cloned the repository and set it up in my local environment and made the changes mentioned. 

![image](https://user-images.githubusercontent.com/61223163/158869315-41205cc2-ec99-4a19-973c-ee95d303f29a.png)
Thank you!

**Comment by jwflory** [comment]
@gnikita432 Looks good! 👍🏻

**Comment by AbihaFatima** [comment]
Hey @jwflory, I made the required changes as per the instructions mentioned above. 
Please take a look! Thanks
![image](https://user-images.githubusercontent.com/70844041/159869116-a25585bd-c525-461f-afe7-bd43f347d847.png)

**Comment by Biki-das** [comment]
hey could anyone guide me a little bit, i am stuck with some error , when i try to run the site i get a config error, could anyone help me with the steps they followed to setup the project?

**Comment by Idadelveloper** [comment]
Since the `config.yml` file is missing you can create a new file at the repo's root and call it `config.yml`.
Copy and paste this and make the necessary edits.

```
---
###############################################################################
#                                                                             #
#                            WEBSITE CONFIGURATION                            #
#                                                                             #
###############################################################################


# --- base website settings ---

baseURL: inventory-hugo-theme
title: your-user-name
languageCode: en-us
enableEmoji: true
enableGitInfo: true

# Optional: Add Google Analytics tracking support.
googleAnalytics: ""


# --- markup settings ---

markup:
  asciidocExt:
    preserveTOC: true
    sectionNumbers: true
  goldmark:
    renderer:
      unsafe: true
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: murphy
    tabWidth: 4


# --- privacy settings ---

privacy:
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
  twitter:
    enableDNT: true
  vimeo:
    enableDNT: true
  youtube:
    privacyEnhanced: true


# --- navigation menu ---

menu:
  main:
    - name: FAQ
      weight: 10
      url: faq

    - name: pages
      weight: 20
      url: pages
      hasChildren: true

    # Sub-pages in this drop-down should correspond to categories created in /content/
    - name: Topic 1
      parent: pages
      weight: 10
      url: topic-1

    - name: Topic 2
      parent: pages
      weight: 20
      url: topic-2

    - name: Topic 3
      parent: pages
      weight: 30
      url: topic-3

    - name: Topic 4
      parent: pages
      weight: 40
      url: topic-4

    - name: Topic 5
      parent: pages
      weight: 50
      url: topic-5


# --- custom settings ---

params:
  logo: "images/logo.png"

  # OpenGraph data
  description: Template site using the UNICEF Inventory theme. This is from the sample configuration.
  author: Our Community of Authors
  image: "images/opengraph.png"

  # customize color
  primary_color: "#4D77FF"
  body_color: "#D8D1C9"
  text_color: "#777779"
  text_color_dark: "#374EA2"
  text_title_color: "#ffffff"
  white_color: "#ffffff"
  light_color: "#f8f9fa"

  # font family (choose from https://fonts.google.com/)
  font_family: "Open+Sans"

  # contact form action (works with https://formspree.io)
  contact_form_action: "#"

  # related article number limit
  article_count: 3

  # brand and identity information
  brand:
    parent_org_name: Example Site
    parent_org_url: https://example.com/
    parent_org_url_legal: https://example.com/privacy/
  footer:
    mainSite: https://unicef-if.discourse.group/c/projects/5
    mainSiteName: UNICEF Innovation Fund projects
    description: Template site using the UNICEF Inventory theme. This is from the sample configuration.


# --- social platform settings ---
# themify icon pack : https://themify.me/themify-icons

  social:
    - icon: ti-github
      name: Theme repository on GitHub
      link: https://github.com/unicef/inventory-hugo-theme
    - icon: ti-twitter
      name: "@GoHugoIO on Twitter"
      link: https://twitter.com/GoHugoIO


# --- taxonomy settings ---
taxonomies:
  alert: alerts
  category: categories
  downloadable: downloadBtn


# --- multilingual settings ---

Languages:
############################# English #############################
  en:
    languageName: en
    languageCode: en-us
    weight: 1
    home: Home
    copyright: Creative Commons BY-SA 4.0. Site theme adapted from UNICEF Inventory theme.
    params:
      banner:
        title: Example Knowledgebase
        subtitle: Template site using the UNICEF Inventory theme. This is from the sample configuration.
        bg_image: images/banner.jpg
        placeholder: Have a question? Search the site here.
############################# Español / Spanish #############################
  # es:
  #   languageName: es
  #   languageCode: es-mx
  #   weight: 2
  #   home: Página principal
  #   copyright: Creative Commons BY-SA 4.0.
  #   params:
  #     banner:
  #       title: "Inventario de Open Source de UNICEF"
  #       subtitle: "Una base de conocimientos de innovación mundial del UNICEF sobre mejores prácticas y recursos para trabajar y dirigir Open."
  #       bg_image: images/banner.jpg
  #       placeholder: ¿Tienes una pregunta? Busque en el sitio aquí.

```
